# Here lies all of the configuration of this program.

# Your New Binusmaya bearer token
# Paste the token without the `Bearer` prefix
# 
# 1. Open the DevTools and go to the Network tab 
# 2. Go to New Binusmaya (login if you havent)
# 3. Look for an authorized HTTP request and copy your token from Request Headers -> `Authorization`
token = "CHANGEME"

# Your Zoom username
# Regardless of what your Zoom default username is, your username will be changed to this
zoom_username = ""
